apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Values.namespace }}"
  name: config-server-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-server-cluster-role
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
    
  - apiGroups: [""]
    resources: [configmaps, services, namespaces, events]
    verbs: [list, watch, create, patch, delete, get]

  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [datalab.tuwien.ac.at]
    resources: [configservers, keyvaluepairs]
    verbs: [list, watch, create, patch, delete, get]

  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: [list, watch, create, patch, delete]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-server-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-server-cluster-role
subjects:
  - kind: ServiceAccount
    name: config-server-service-account
    namespace: "{{ .Values.namespace }}"
