apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configservers.datalab.tuwien.ac.at
spec:
  scope: Namespaced
  group: datalab.tuwien.ac.at
  names:
    kind: ConfigServer
    plural: configservers
    singular: configserver
    shortNames:
      - cfg-server
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                containerPort:
                  type: integer
                configMountPath:
                  type: string