apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keyvaluepairs.datalab.tuwien.ac.at
spec:
  scope: Namespaced
  group: datalab.tuwien.ac.at
  names:
    kind: KeyValuePair
    plural: keyvaluepairs
    singular: keyvaluepair
    shortNames:
      - kvpair
      - kvp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
                key:
                  type: string
                value:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
