apiVersion: datalab.tuwien.ac.at/v1
kind: ConfigServer
metadata:
  name: minimal-config
  namespace: config-server
spec:
  image: ghcr.io/tu-wien-datalab/config-server:main
  imagePullPolicy: IfNotPresent
  containerPort: 80
  configMountPath: /var/lib/config-server
