apiVersion: datalab.tuwien.ac.at/v1
kind: ConfigServer
metadata:
  name: minimal-config
  namespace: config-server
spec:
  image: config-server:latest
  imagePullPolicy: Never
  containerPort: 80
  configMountPath: /var/lib/config-server
