name: ci

on:
  push:
    branches:
      - main
    tags:
      - "operator-v*"
      - "server-v*"
  pull_request:
    branches: '*'

jobs:
  changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      changeDirs: ${{ steps.outputStep.outputs.changeDirs }}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed dirs                  # To check if any files changed in a directory
        id: changeDirsStep
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          files: |
            **
      - id: outputStep
        run: echo "changeDirs=${{ steps.changeDirsStep.outputs.all_changed_files }}" >> $GITHUB_OUTPUT


  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r testing.requirements.txt
          pip install -r srv/requirements.txt

      - name: Run tests
        run: pytest tests/server_tests

  operator-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Setup k3s test cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install -r testing.requirements.txt
          pip install -r opr/requirements.txt

      - name: Run tests
        run: pytest tests/operator_tests

  docker:
    runs-on: ubuntu-latest
    needs:
      - changed-dirs
      - server-tests
      - operator-tests
    if: contains(needs.changed-dirs.outputs.changeDirs, 'opr') || contains(needs.changed-dirs.outputs.changeDirs, 'srv')
    strategy:
      matrix:
        include:
          - image: ghcr.io/tu-wien-datalab/config-server-operator
            directory: opr
            version-pattern: operator-v(\d.+)
          - image: ghcr.io/tu-wien-datalab/config-server
            directory: srv
            version-pattern: server-v(\d.+)
    steps:
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ matrix.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=match,pattern=${{ matrix.pattern }},group=1
            type=sha

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        if: contains(needs.changed-dirs.outputs.changeDirs, matrix.directory)
        with:
          context: ${{ matrix.directory }}
          file: ./${{ matrix.directory }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}